import { Activity, AlertTriangle, BarChart3, Bell, Check, Eye, Network, Package, Search, Truck, Warehouse, Zap } from "lucide-react";
import { Link } from "react-router-dom";

const workflow = [
  { number: "01", title: "MONITOR", text: "See the network in real time.", icon: Eye },
  { number: "02", title: "INVESTIGATE", text: "Understand what is changing and why.", icon: Search },
  { number: "03", title: "ACT", text: "Reroute, reassign, prioritize and respond.", icon: Zap },
  { number: "04", title: "MEASURE", text: "See whether the decision improved the operation.", icon: BarChart3 },
];

const ecosystem = [
  ["Network", "See the entire logistics network in motion.", Network],
  ["Routes", "Understand route performance, traffic and disruption.", Activity],
  ["Fleet", "Monitor vehicle movement, health and utilization.", Truck],
  ["Warehouses", "Understand capacity, throughput and hub operations.", Warehouse],
  ["Shipments", "Track individual shipments from origin to destination.", Package],
  ["Alerts", "Identify what needs attention right now.", AlertTriangle],
  ["Analytics", "Understand performance and operational trends.", BarChart3],
];

const differentiators = [
  ["LIVE VISIBILITY", "Understand what is happening across the network right now."],
  ["CONNECTED CONTEXT", "See how shipments, vehicles, warehouses and routes influence one another."],
  ["OPERATIONAL CONTROL", "Move from identifying a problem to taking action."],
  ["MEASURABLE IMPACT", "Understand whether the action actually improved the operation."],
];

function SectionLabel({ children }) {
  return <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-[#38BDF8]">{children}</p>;
}

function About() {
  return <main className="min-h-screen overflow-hidden bg-[#020812] text-[#F5F7FA] lg:ml-[248px]"><div className="mx-auto max-w-[1440px] px-6 sm:px-8 lg:px-12">
    <section className="relative grid min-h-[620px] items-center border-b border-[#18304A] py-24 lg:grid-cols-[1fr_0.85fr] lg:gap-20 lg:py-32"><div className="pointer-events-none absolute -right-40 top-20 h-72 w-72 rounded-full bg-[#2196F3]/[0.06] blur-[110px]" /><div className="relative z-10"><SectionLabel>ABOUT INMOTION</SectionLabel><h1 className="mt-7 max-w-[700px] text-5xl font-bold leading-[0.94] tracking-[-0.055em] text-white sm:text-6xl lg:text-[78px]">LOGISTICS<br />SHOULD NEVER<br /><span className="text-[#2196F3]">STAND STILL.</span></h1><p className="mt-8 max-w-[560px] text-[15px] leading-8 text-[#A7B3C2]">InMotion connects the moving parts of modern logistics into one intelligent operational system — giving teams the visibility and control to keep everything moving.</p></div><div className="relative mx-auto w-full max-w-[390px] py-10 lg:py-0"><div className="border-y border-[#18304A] py-6"><p className="text-[10px] font-semibold tracking-[0.18em] text-[#6F7D8E]">CONNECTED SYSTEM</p>{[["SHIPMENTS", Package], ["WAREHOUSES", Warehouse], ["ROUTES", Network], ["VEHICLES", Truck], ["DECISIONS", Check]].map(([label, Icon], index) => <div key={label} className="relative flex items-center gap-4 py-4"><div className="relative flex h-9 w-9 items-center justify-center border border-[#285074] bg-[#07111F] text-[#38BDF8]"><Icon size={16} /></div><span className="text-[11px] font-semibold tracking-[0.15em] text-[#C5D1DE]">{label}</span>{index < 4 && <span className="absolute left-[18px] top-[52px] h-8 w-px bg-[#285074]" />}</div>)}</div></div></section>

    <section className="grid gap-14 border-b border-[#18304A] py-24 lg:grid-cols-[0.85fr_1fr] lg:gap-28 lg:py-32"><div><SectionLabel>THE PLATFORM</SectionLabel><h2 className="mt-6 max-w-[520px] text-4xl font-semibold leading-[1.02] tracking-[-0.045em] text-white sm:text-5xl">ONE NETWORK.<br /><span className="text-[#2196F3]">ONE CONTROL CENTER.</span></h2><p className="mt-10 max-w-[360px] text-2xl font-medium leading-[1.25] tracking-[-0.03em] text-[#E5EDF6]">SEE EVERYTHING.<br />UNDERSTAND WHAT MATTERS.</p></div><div className="max-w-[570px] self-end text-[15px] leading-8 text-[#A7B3C2]"><p>InMotion brings shipments, vehicles, warehouses and routes into one connected operational view.</p><p className="mt-6">Instead of switching between disconnected tools, teams can monitor activity, investigate exceptions, take action and measure the result from a single control center.</p></div></section>

    <section className="border-b border-[#18304A] py-24 lg:py-32"><SectionLabel>THE PROBLEM</SectionLabel><div className="mt-6 grid gap-14 lg:grid-cols-[0.9fr_1fr] lg:gap-24"><div><h2 className="text-4xl font-semibold leading-[1.02] tracking-[-0.045em] text-white sm:text-5xl">LOGISTICS DOESN'T<br />BREAK IN ONE PLACE.</h2><p className="mt-8 max-w-[500px] text-[15px] leading-8 text-[#A7B3C2]">A shipment can be delayed because a vehicle is late. A vehicle can be late because a route is congested. A route can slow down because a warehouse is overloaded.</p></div><div className="grid max-w-[420px] gap-0"><div className="border-l border-[#285074] pl-5">{["SHIPMENT", "VEHICLE", "ROUTE", "WAREHOUSE", "NETWORK"].map((item, index) => <div key={item} className="relative py-3 text-[12px] font-semibold tracking-[0.18em] text-[#C5D1DE]">{item}{index < 4 && <span className="absolute -bottom-1 left-[-4px] h-2 w-2 rounded-full bg-[#2196F3]" />}</div>)}</div><p className="mt-10 border-t border-[#18304A] pt-6 text-2xl font-medium leading-[1.15] tracking-[-0.03em] text-[#F5F7FA]">ONE CHANGE CAN AFFECT<br /><span className="text-[#2196F3]">THE ENTIRE NETWORK.</span></p></div></div></section>

    <section className="border-b border-[#18304A] py-24 lg:py-32"><SectionLabel>OUR APPROACH</SectionLabel><div className="mt-6 grid gap-12 lg:grid-cols-2 lg:items-end"><h2 className="text-4xl font-semibold leading-[1.02] tracking-[-0.045em] text-white sm:text-5xl">FROM INFORMATION<br /><span className="text-[#2196F3]">TO ACTION.</span></h2><div><p className="max-w-[520px] text-[15px] leading-8 text-[#A7B3C2]">Traditional operational dashboards often stop at showing what happened. InMotion is designed to go further.</p><div className="mt-8 flex flex-wrap items-center gap-3 text-[11px] font-semibold tracking-[0.12em] text-[#C5D1DE]"><span>VISIBILITY</span><span className="text-[#2196F3]">→</span><span>CONTEXT</span><span className="text-[#2196F3]">→</span><span>ACTION</span><span className="text-[#2196F3]">→</span><span>OUTCOME</span></div></div></div></section>

    <section className="border-b border-[#18304A] py-24 lg:py-28"><SectionLabel>THE OPERATING LOOP</SectionLabel><h2 className="mt-6 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">MONITOR → INVESTIGATE → ACT → MEASURE</h2><div className="mt-14 grid gap-0 md:grid-cols-4">{workflow.map(({ number, title, text, icon: Icon }, index) => <div key={title} className="relative border-l border-[#285074] py-2 pl-5 pr-6 md:min-h-[150px] md:border-t md:pt-6"><span className="text-[10px] font-semibold tracking-[0.18em] text-[#38BDF8]">{number}</span><Icon size={17} className="mt-6 text-[#2196F3]" /><h3 className="mt-4 text-[13px] font-semibold tracking-[0.12em] text-white">{title}</h3><p className="mt-2 text-[12px] leading-5 text-[#7F91A5]">{text}</p>{index < workflow.length - 1 && <span className="absolute -right-1 top-[-4px] hidden h-2 w-2 rounded-full bg-[#2196F3] md:block" />}</div>)}</div></section>

    <section className="border-b border-[#18304A] py-24 lg:py-32"><SectionLabel>ONE SYSTEM</SectionLabel><h2 className="mt-6 text-4xl font-semibold tracking-[-0.045em] text-white sm:text-5xl">EVERYTHING IS <span className="text-[#2196F3]">CONNECTED.</span></h2><div className="relative mx-auto mt-16 max-w-[720px] border-y border-[#18304A] py-12"><div className="mx-auto flex h-24 w-40 items-center justify-center border border-[#2196F3]/60 bg-[#07111F] text-center text-[11px] font-semibold tracking-[0.14em] text-white shadow-[0_0_24px_rgba(33,150,243,0.08)]">INMOTION<br /><span className="text-[#38BDF8]">CONTROL CENTER</span></div><div className="grid grid-cols-2 gap-10 pt-10 text-center sm:grid-cols-3">{[["SHIPMENTS", Package], ["VEHICLES", Truck], ["WAREHOUSES", Warehouse], ["ROUTES", Network], ["ALERTS", Bell], ["ANALYTICS", BarChart3]].map(([label, Icon]) => <div key={label} className="flex flex-col items-center gap-2 text-[10px] font-semibold tracking-[0.14em] text-[#A7B3C2]"><Icon size={17} className="text-[#38BDF8]" />{label}</div>)}</div></div></section>

    <section className="border-b border-[#18304A] py-24 lg:py-32"><SectionLabel>WHY INMOTION</SectionLabel><h2 className="mt-6 max-w-[700px] text-4xl font-semibold leading-[1.02] tracking-[-0.045em] text-white sm:text-5xl">BUILT FOR DECISIONS.<br /><span className="text-[#2196F3]">NOT JUST DATA.</span></h2><div className="mt-14 grid gap-x-10 gap-y-10 sm:grid-cols-2">{differentiators.map(([title, text], index) => <div key={title} className="border-t border-[#18304A] pt-5"><span className="text-[10px] tracking-[0.18em] text-[#38BDF8]">0{index + 1}</span><h3 className="mt-4 text-[13px] font-semibold tracking-[0.12em] text-white">{title}</h3><p className="mt-3 max-w-[300px] text-[13px] leading-6 text-[#7F91A5]">{text}</p></div>)}</div></section>

    <section className="border-b border-[#18304A] py-24 lg:py-28"><div className="grid gap-12 lg:grid-cols-2"><div><SectionLabel>PRODUCT ECOSYSTEM</SectionLabel><h2 className="mt-6 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">THE SYSTEM IS ONLY<br /><span className="text-[#2196F3]">AS STRONG AS ITS CONNECTIONS.</span></h2></div><div>{ecosystem.map(([title, text, Icon]) => <Link key={title} to={title === "Network" ? "/app/network" : title === "Routes" ? "/app/network/routes" : title === "Fleet" ? "/app/fleet" : title === "Warehouses" ? "/app/warehouses" : title === "Alerts" ? "/app/alerts" : title === "Analytics" ? "/app/analytics" : "/app/shipments"} className="group flex items-center gap-4 border-b border-[#18304A] py-4"><Icon size={17} className="text-[#38BDF8]" /><span className="w-28 shrink-0 text-[12px] font-semibold tracking-[0.1em] text-white">{title.toUpperCase()}</span><span className="flex-1 text-[12px] text-[#7F91A5] group-hover:text-[#C5D1DE]">{text}</span><span className="text-[#38516B] transition-transform group-hover:translate-x-1">→</span></Link>)}</div></div></section>

    <section className="border-b border-[#18304A] py-24 lg:py-32"><div className="mx-auto max-w-[760px] text-center"><SectionLabel>THE HUMAN SIDE</SectionLabel><h2 className="mt-6 text-4xl font-semibold leading-[1.05] tracking-[-0.045em] text-white sm:text-5xl">BUILT FOR THE PEOPLE<br /><span className="text-[#2196F3]">KEEPING THE NETWORK MOVING.</span></h2><p className="mx-auto mt-8 max-w-[610px] text-[15px] leading-8 text-[#A7B3C2]">Every shipment represents a promise. Every route represents a decision. Every warehouse represents a point of coordination. Every vehicle represents movement.</p><p className="mx-auto mt-5 max-w-[610px] text-[15px] leading-8 text-[#A7B3C2]">InMotion brings those pieces together so operations teams can spend less time searching for answers and more time making decisions.</p></div></section>

    <section className="py-28 text-center lg:py-36"><SectionLabel>INMOTION</SectionLabel><h2 className="mt-7 text-5xl font-bold leading-[0.94] tracking-[-0.055em] text-white sm:text-7xl">THE WORLD<br />KEEPS <span className="text-[#2196F3]">MOVING.</span></h2><p className="mt-8 text-2xl font-medium tracking-[-0.03em] text-[#E5EDF6]">SO SHOULD<br />YOUR OPERATIONS.</p><p className="mt-8 text-[13px] tracking-[0.08em] text-[#7F91A5]">Connected operations. Clear decisions. Better outcomes.</p></section>

    <footer className="border-t border-[#18304A] py-10"><div className="flex flex-col gap-8 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[17px] font-bold tracking-[0.14em] text-white">INMOTION</p><p className="mt-2 text-[10px] font-semibold tracking-[0.2em] text-[#38BDF8]">LOGISTICS CONTROL</p><p className="mt-5 text-[12px] text-[#6F7D8E]">Keep the world in motion.</p></div><div className="flex max-w-[520px] flex-wrap gap-x-5 gap-y-3 text-[12px] text-[#7F91A5]">{[["Network", "/app/network"], ["Routes", "/app/network/routes"], ["Fleet", "/app/fleet"], ["Warehouses", "/app/warehouses"], ["Shipments", "/app/shipments"], ["Alerts", "/app/alerts"], ["Analytics", "/app/analytics"], ["Settings", "/app/settings"]].map(([label, to]) => <Link key={label} to={to} className="hover:text-white">{label}</Link>)}</div></div><div className="mt-8 border-t border-[#18304A] pt-5 text-[10px] text-[#53677D]">INMOTION CONTROL CENTER · Connected operations, made visible.</div></footer>
  </div></main>;
}

export default About;
